name: Update nightly Rust
on:
  schedule:
    - cron: "29 17 1 * *" # At 17:29 on day-of-month 1.
  workflow_dispatch: # allows manual triggering
env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  format:
    name: Update nightly Rustc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@a02741459ec5e501b9843ed30b535ca0a0376ae4 # nightly
      - name: Update rust-toolchain.toml to use latest nightly
        run: |
          set -xe

          # Get the latest nightly date.
          # If the latest nightly date is not the same as the current nightly date,
          # rustup will default to the latest nightly up to TODAY.
          #
          # Example: If the latest nightly is 2023-07-01, and the TODAY is 2023-07-02,
          # then rustup will default to nightly-2023-07-01.
          TODAY="$(date +%Y-%m-%d)"

          # Update the nightly version in the rust-toolchain.toml file.
          echo "Updating rust-toolchain.toml to use nightly-$TODAY"
          sed -i "s/^channel = \"nightly-.*\"/channel = \"nightly-$TODAY\"/" rust-toolchain.toml

          # Update the nightly date in the environment.
          echo "nightly_date=${TODAY}" >> "$GITHUB_ENV"

          # Maybe there is no new nightly.
          # In this case don't make an empty PR.
          if ! git diff --exit-code > /dev/null; then
              echo "Updated nightly. Opening PR."
              echo "changes_made=true" >> "$GITHUB_ENV"
          else
              echo "Attempted to update nightly but the latest-nightly date did not change. Not opening any PR."
              echo "changes_made=false" >> "$GITHUB_ENV"
          fi
      - name: Create Pull Request
        if: env.changes_made == 'true'
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v7
        env:
          NIGHTLY_DATE: ${{ env.nightly_date }}
        with:
          author: Update Nightly Rustc Bot <no-reply@alpenlabs.io>
          committer: Update Nightly Rustc Bot <no-reply@alpenlabs.io>
          title: Automated update to rustc (to nightly-$NIGHTLY_DATE)
          body: |
            Automated update to Rust nightly by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          commit-message: Automated update to Rust nightly-$NIGHTLY_DATE
          branch: create-pull-request/automated-nightly-update
